### ISSUE TITLE
getting "[error]	TypeError: Cannot read properties of undefined (reading 'create')"

### ISSUE THREAD

**Issue by frankfnord** [arbs-io/vscode-openai-docs#11] opened 2023-05-10 16:46 UTC
i get "[error]	TypeError: Cannot read properties of undefined (reading 'create')". it does not matter which service provider I choose. 

2023-05-10 16:39:57.852 [info]	activate vscode-openai
2023-05-10 16:40:18.626 [error]	Request failed with status code 401
2023-05-10 16:40:33.683 [info]	ServiceProvider (OpenAI): https://api.openai.com/v1 gpt-3.5-turbo-0301
2023-05-10 16:40:34.772 [info]	verifyApiKey success
2023-05-10 16:40:42.734 [error]	TypeError: Cannot read properties of undefined (reading 'create')
2023-05-10 16:42:39.551 [info]	verifyApiKey success
2023-05-10 16:42:41.918 [info]	ServiceProvider (VSCode-OpenAI)
2023-05-10 16:42:51.495 [error]	TypeError: Cannot read properties of undefined (reading 'create')

After restarting vscode, the vscode-openai plugin is not visible at all. I have to enter settings, switch the provider to get the plugin button. 

any idea what I am doing wrong?

**Comment by coolvivz** [comment] 2023-05-10 17:46
Actually, I faced this too. I reinstalled and worked fine

**Comment by frankfnord** [comment] 2023-05-10 18:42
i already tried reinstalling, even starting with a clean vscode profile but neither worked.

**Comment by arbs-io** [comment] 2023-05-11 15:10
I'm improving the telemetry as it's hard to replicate scenario. This should be added shortly. Once in place I should be able to resolve the issues.
I've seen notice issues when webviews are slow to load. I'm changing the initial creation of conversation to accommodate potential race conditions.

**Comment by coolvivz** [comment] 2023-05-12 13:59
> I'm improving the telemetry as it's hard to replicate scenario. This should be added shortly. Once in place I should be able to resolve the issues. I've seen notice issues when webviews are slow to load. I'm changing the initial creation of conversation to accommodate potential race conditions.

**Comment by coolvivz** [comment] 2023-05-12 14:01
Thanks Andrew. One more thing I have noticed is we have to reload the extension every time we open the VS. Have you noticed  it ?

**Comment by arbs-io** [comment] 2023-05-14 10:43
I think that's because I've been rolling out a few updates recently. Once a day for the last few days. These updates are to handle an issue gracefully. Hopefully the issue is now resolved. I've seen a lot of users without git which was causing issues.

**Comment by frankfnord** [comment] 2023-05-14 19:21
> I think that's because I've been rolling out a few updates recently. Once a day for the last few days. These updates are to handle an issue gracefully. Hopefully the issue is now resolved. I've seen a lot of users without git which was causing issues.

indeed. installing git locally fixed this issue for me as well.

**Comment by arbs-io** [comment] 2023-05-14 22:14
Brilliant! Thanks so much for all the feedback. It truly is appreciated. 

I'll close this issue. If there are any other issues or enhancements, please help me by raising an issue.
I'm working on resource integration to use websites or documents to use more up-to-date information when asking questions. It should be available soon.

Please leave a review on the marketplace for any feedback to help improve the product.

**Closed as completed by arbs-io** 2023-05-14 22:14 UTC
